### ISSUE TITLE
`.` in user name

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/dt-review-bot#2]
I've noticed some user names being prefixed with `.`. Such as [`@.benjaminjackman`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13649#issuecomment-269833661) (derived from `Benjamin Jackman <https://github.com/benjaminjackman>`, which has no `.`).

**Comment by vvakame** [comment]
Oh, it is intentional.

please check below links 😉 
https://github.com/DefinitelyTyped/dt-review-tool/blob/5e959f3a5af38bbbead0bb5e47ef7441ed99f53a/lib/index.ts#L125-L135
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11624

**Comment by ghost** [comment]
OK then.
Do you know why this is a separate repository from `dt-review-tool`?

**Comment by vvakame** [comment]
because use it as a CLI.
I'm using it from commandline. but not uses `npm install dt-review-tool`.
